locale: "en-US"
title: RodrigoMorenoEng # Title of your site
url: "http://rroderickk.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
google_analytics_key: "G-VVZQ43P737"

# Default description in social shares for the jekyll-seo-tag gem
description: > # this means to ignore newlines until "baseurl:"
  Python programming sofware razacodes.io metaverse update rython rodrigo moreno rodrigo moreno rroderickk roderick WUNDERMAN THOMPSON INTELLIGENCE

# Author details for the jekyll-seo-tag gem
author:
  name: Rodrigo Moreno
  email: rroderickk@gmail.com
  LinkedIn: https://www.linkedin.com/in/rodrigo-moreno-rr

# Social details for the jekyll-seo-tag gem
social:
  name: Strata Reloaded Template
  links:
    - Github: https://rroderickk.github.io/
    - LinkedIn: https://www.linkedin.com/in/rodrigo-moreno-rr


permalink: pretty

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-sitemap"

# Jekyll SEO Tag
webmaster_verifications:
  google: # 1234
  bing: # 1234
  alexa: # 1234
  yandex: # 1234

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

theme: jekyll-theme-hacker
